### ISSUE TITLE
sid timeout for long-lasting instances

### ISSUE THREAD

**Issue by cmsimike** [snjoetw/py-synology#3]
Hi,

I have come from the home-assistant community where we're having an issue around SIDs expiring and causing any instanced SurveillanceStation instances to become stale, requiring a full restart of the app.

What are your thoughts about your library silently re-establishing connections in cases like that? Meaning when you get an exception from Synology:
https://github.com/home-assistant/home-assistant/issues/12037

Just recreate the API?

**Comment by snjoetw** [comment]
Thanks for raising this, I'll have a look this weekend to see what should be done. Ideally this should be handled inside this lib

**Comment by cmsimike** [comment]
@snjoetw Thank you for the response! I'll put my hass PR into a WIP state (I fix this manually in there) but if the connection can be re-established inside your lib, I think that would be the absolute best.

**Comment by snjoetw** [comment]
@cmsimike what do you think of this PR? https://github.com/snjoetw/py-synology/pull/4

**Comment by cmsimike** [comment]
@snjoetw Thank you for your work on this, and apologies for the delay in getting back to you. I will test this out and let you know.

**Comment by cmsimike** [comment]
Installed! Ill report back in a few days.

**Comment by snjoetw** [comment]
Thanks! Hopefully this fixes your problem.

btw how do you reproduce it? Do you just leave it run for a few days and it’ll start erroring out?

It’s weird that I’ve never seen the error myself. I have a DS216+II with DSM 6.2

**Comment by cmsimike** [comment]
Exactly that. I (unfortunately) never paid too much attention when it goes out but eventually after a few days the cameras won't load anymore and I am spammed in the log with exception.

**Comment by snjoetw** [comment]
Closing this one and will integrate with next home assistant release
